[2025-02-06T10:08:20.112+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T10:08:20.134+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.task_1 scheduled__2025-01-01T05:34:30+00:00 [queued]>
[2025-02-06T10:08:20.155+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.task_1 scheduled__2025-01-01T05:34:30+00:00 [queued]>
[2025-02-06T10:08:20.156+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-06T10:08:20.191+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): task_1> on 2025-01-01 05:34:30+00:00
[2025-02-06T10:08:20.195+0000] {standard_task_runner.py:72} INFO - Started process 2272 to run task
[2025-02-06T10:08:20.198+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'task_1', 'scheduled__2025-01-01T05:34:30+00:00', '--job-id', '1666', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpnkkyuexc']
[2025-02-06T10:08:20.199+0000] {standard_task_runner.py:105} INFO - Job 1666: Subtask task_1
[2025-02-06T10:08:20.280+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.task_1 scheduled__2025-01-01T05:34:30+00:00 [running]> on host 1f20f9aee2e1
[2025-02-06T10:08:20.384+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T05:34:30+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T05:34:30+00:00'
[2025-02-06T10:08:20.386+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-06T10:08:20.386+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-06T10:08:20.387+0000] {logging_mixin.py:190} INFO - Current task name:task_1 state:running start_date:2025-02-06 10:08:20.134921+00:00
[2025-02-06T10:08:20.387+0000] {logging_mixin.py:190} INFO - Dag name:my_first_dag and current dag run status:running
[2025-02-06T10:08:20.388+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T10:08:20.389+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/first_dag.py", line 17, in print_hello
    ti.xcom_pull(tak)
                 ^^^
NameError: name 'tak' is not defined
[2025-02-06T10:08:20.404+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-06T10:08:20.405+0000] {logging_mixin.py:190} INFO - Task start:2025-02-06 10:08:20.134921+00:00 end:2025-02-06 10:08:20.404454+00:00 duration:0.269533
[2025-02-06T10:08:20.405+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): task_1> dag:<DAG: my_first_dag> dagrun:<DagRun my_first_dag @ 2025-01-01 05:34:30+00:00: scheduled__2025-01-01T05:34:30+00:00, state:running, queued_at: 2025-02-06 10:07:55.634576+00:00. externally triggered: False>
[2025-02-06T10:08:20.406+0000] {logging_mixin.py:190} INFO - Failure caused by name 'tak' is not defined
[2025-02-06T10:08:20.406+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=my_first_dag, task_id=task_1, run_id=scheduled__2025-01-01T05:34:30+00:00, execution_date=20250101T053430, start_date=20250206T100820, end_date=20250206T100820
[2025-02-06T10:08:20.439+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T10:08:20.440+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1666 for task task_1 (name 'tak' is not defined; 2272)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/first_dag.py", line 17, in print_hello
    ti.xcom_pull(tak)
                 ^^^
NameError: name 'tak' is not defined
[2025-02-06T10:08:20.452+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-06T10:08:20.474+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-06T10:08:20.497+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
