[2025-02-06T09:29:02.273+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T09:29:02.289+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.task_random_choice scheduled__2025-01-01T03:45:30+00:00 [queued]>
[2025-02-06T09:29:02.308+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.task_random_choice scheduled__2025-01-01T03:45:30+00:00 [queued]>
[2025-02-06T09:29:02.309+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-06T09:29:02.343+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): task_random_choice> on 2025-01-01 03:45:30+00:00
[2025-02-06T09:29:02.346+0000] {standard_task_runner.py:72} INFO - Started process 87 to run task
[2025-02-06T09:29:02.349+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'task_random_choice', 'scheduled__2025-01-01T03:45:30+00:00', '--job-id', '872', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp6b09jijq']
[2025-02-06T09:29:02.350+0000] {standard_task_runner.py:105} INFO - Job 872: Subtask task_random_choice
[2025-02-06T09:29:02.428+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.task_random_choice scheduled__2025-01-01T03:45:30+00:00 [running]> on host 44d2379f0be5
[2025-02-06T09:29:02.553+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='task_random_choice' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T03:45:30+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T03:45:30+00:00'
[2025-02-06T09:29:02.554+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-06T09:29:02.555+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-06T09:29:02.555+0000] {logging_mixin.py:190} INFO - Current task name:task_random_choice state:running start_date:2025-02-06 09:29:02.290497+00:00
[2025-02-06T09:29:02.555+0000] {logging_mixin.py:190} INFO - Dag name:my_first_dag and current dag run status:running
[2025-02-06T09:29:02.556+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T09:29:02.557+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-06T09:29:02.557+0000] {python.py:240} INFO - Done. Returned value was: task_2
[2025-02-06T09:29:02.558+0000] {branch.py:38} INFO - Branch into task_2
[2025-02-06T09:29:02.558+0000] {skipmixin.py:230} INFO - Following branch ('task_2',)
[2025-02-06T09:29:02.562+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-06T09:29:02.563+0000] {process_utils.py:132} INFO - Sending 15 to group 87. PIDs of all processes in the group: [87]
[2025-02-06T09:29:02.564+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 87
[2025-02-06T09:29:02.570+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-06T09:29:02.583+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/operators/branch.py", line 40, in do_branch
    self.skip_all_except(context["ti"], branch_task_ids)
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 189, in skip_all_except
    SkipMixin._skip_all_except(ti=ti, branch_task_ids=branch_task_ids)
  File "/opt/conda/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 270, in _skip_all_except
    downstream_ti := dag_run.get_task_instance(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/dagrun.py", line 647, in get_task_instance
    return DagRun.fetch_task_instance(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/dagrun.py", line 673, in fetch_task_instance
    return session.scalars(
           ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1778, in scalars
    return self.execute(
           ^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/conda/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2138, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/opt/conda/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/conda/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/opt/conda/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-02-06T09:29:02.598+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-06T09:29:02.599+0000] {logging_mixin.py:190} INFO - Task start:2025-02-06 09:29:02.290497+00:00 end:2025-02-06 09:29:02.597701+00:00 duration:0.307204
[2025-02-06T09:29:02.599+0000] {logging_mixin.py:190} INFO - Task:<Task(BranchPythonOperator): task_random_choice> dag:<DAG: my_first_dag> dagrun:<DagRun my_first_dag @ 2025-01-01 03:45:30+00:00: scheduled__2025-01-01T03:45:30+00:00, state:running, queued_at: 2025-02-06 09:28:48.720291+00:00. externally triggered: False>
[2025-02-06T09:29:02.600+0000] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2025-02-06T09:29:02.601+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=my_first_dag, task_id=task_random_choice, run_id=scheduled__2025-01-01T03:45:30+00:00, execution_date=20250101T034530, start_date=20250206T092902, end_date=20250206T092902
