[2025-02-06T10:03:28.611+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T10:03:28.636+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.task_2 scheduled__2025-01-01T05:22:00+00:00 [queued]>
[2025-02-06T10:03:28.662+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.task_2 scheduled__2025-01-01T05:22:00+00:00 [queued]>
[2025-02-06T10:03:28.664+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-06T10:03:28.702+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): task_2> on 2025-01-01 05:22:00+00:00
[2025-02-06T10:03:28.706+0000] {standard_task_runner.py:72} INFO - Started process 1843 to run task
[2025-02-06T10:03:28.708+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'task_2', 'scheduled__2025-01-01T05:22:00+00:00', '--job-id', '1592', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp41sxqvt4']
[2025-02-06T10:03:28.709+0000] {standard_task_runner.py:105} INFO - Job 1592: Subtask task_2
[2025-02-06T10:03:28.782+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.task_2 scheduled__2025-01-01T05:22:00+00:00 [running]> on host 1f20f9aee2e1
[2025-02-06T10:03:28.881+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='task_2' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T05:22:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T05:22:00+00:00'
[2025-02-06T10:03:28.883+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-06T10:03:28.883+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-06T10:03:28.883+0000] {logging_mixin.py:190} INFO - Current task name:task_2 state:running start_date:2025-02-06 10:03:28.637290+00:00
[2025-02-06T10:03:28.884+0000] {logging_mixin.py:190} INFO - Dag name:my_first_dag and current dag run status:running
[2025-02-06T10:03:28.884+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T10:03:28.885+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/first_dag.py", line 17, in print_hello
    ti.xc
    ^^^^
AttributeError: 'TaskInstance' object has no attribute 'x'
[2025-02-06T10:03:28.900+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-06T10:03:28.901+0000] {logging_mixin.py:190} INFO - Task start:2025-02-06 10:03:28.637290+00:00 end:2025-02-06 10:03:28.900465+00:00 duration:0.263175
[2025-02-06T10:03:28.901+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): task_2> dag:<DAG: my_first_dag> dagrun:<DagRun my_first_dag @ 2025-01-01 05:22:00+00:00: scheduled__2025-01-01T05:22:00+00:00, state:running, queued_at: 2025-02-06 10:03:10.543072+00:00. externally triggered: False>
[2025-02-06T10:03:28.902+0000] {logging_mixin.py:190} INFO - Failure caused by 'TaskInstance' object has no attribute 'x'
[2025-02-06T10:03:28.902+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=my_first_dag, task_id=task_2, run_id=scheduled__2025-01-01T05:22:00+00:00, execution_date=20250101T052200, start_date=20250206T100328, end_date=20250206T100328
[2025-02-06T10:03:28.937+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T10:03:28.938+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1592 for task task_2 ('TaskInstance' object has no attribute 'x'; 1843)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/first_dag.py", line 17, in print_hello
    ti.xc
    ^^^^
AttributeError: 'TaskInstance' object has no attribute 'x'
[2025-02-06T10:03:28.961+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-06T10:03:28.982+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-06T10:03:29.004+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
