[2025-02-06T09:05:11.038+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T09:05:11.055+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.task_random_choice scheduled__2025-01-01T01:40:30+00:00 [queued]>
[2025-02-06T09:05:11.068+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.task_random_choice scheduled__2025-01-01T01:40:30+00:00 [queued]>
[2025-02-06T09:05:11.069+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-06T09:05:11.108+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): task_random_choice> on 2025-01-01 01:40:30+00:00
[2025-02-06T09:05:11.111+0000] {standard_task_runner.py:72} INFO - Started process 122 to run task
[2025-02-06T09:05:11.113+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'task_random_choice', 'scheduled__2025-01-01T01:40:30+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpgpw9dytp']
[2025-02-06T09:05:11.114+0000] {standard_task_runner.py:105} INFO - Job 365: Subtask task_random_choice
[2025-02-06T09:05:11.144+0000] {cli_action_loggers.py:177} WARNING - Failed to log action (sqlite3.OperationalError) disk I/O error
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-02-06T09:05:11.206+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.task_random_choice scheduled__2025-01-01T01:40:30+00:00 [running]> on host 6f30e18c7b14
[2025-02-06T09:05:11.313+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='task_random_choice' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T01:40:30+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T01:40:30+00:00'
[2025-02-06T09:05:11.314+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-06T09:05:11.314+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-06T09:05:11.315+0000] {logging_mixin.py:190} INFO - Current task name:task_random_choice state:running start_date:2025-02-06 09:05:11.055587+00:00
[2025-02-06T09:05:11.315+0000] {logging_mixin.py:190} INFO - Dag name:my_first_dag and current dag run status:running
[2025-02-06T09:05:11.316+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T09:05:11.316+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-06T09:05:11.317+0000] {python.py:240} INFO - Done. Returned value was: task_1
[2025-02-06T09:05:11.317+0000] {branch.py:38} INFO - Branch into task_1
[2025-02-06T09:05:11.318+0000] {skipmixin.py:230} INFO - Following branch ('task_1',)
[2025-02-06T09:05:11.330+0000] {skipmixin.py:278} INFO - Skipping tasks [('task_2', -1)]
[2025-02-06T09:05:11.398+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T09:05:11.399+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=task_random_choice, run_id=scheduled__2025-01-01T01:40:30+00:00, execution_date=20250101T014030, start_date=20250206T090511, end_date=20250206T090511
[2025-02-06T09:05:11.432+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-06T09:05:11.433+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-06T09:05:11.433+0000] {logging_mixin.py:190} INFO - Dag name:my_first_dag queued_at:2025-02-06 09:05:09.529292+00:00
[2025-02-06T09:05:11.434+0000] {logging_mixin.py:190} INFO - Task hostname:6f30e18c7b14 operator:BranchPythonOperator
[2025-02-06T09:05:11.447+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-06T09:05:11.489+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-06T09:05:11.504+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
