[2025-02-06T15:17:36.549+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T15:17:36.577+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_training_dag.task_train_model scheduled__2025-01-01T00:21:00+00:00 [queued]>
[2025-02-06T15:17:36.595+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_training_dag.task_train_model scheduled__2025-01-01T00:21:00+00:00 [queued]>
[2025-02-06T15:17:36.595+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-06T15:17:36.634+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): task_train_model> on 2025-01-01 00:21:00+00:00
[2025-02-06T15:17:36.642+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'my_training_dag', 'task_train_model', 'scheduled__2025-01-01T00:21:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/training_dag.py', '--cfg-path', '/tmp/tmpi_06anm5']
[2025-02-06T15:17:36.644+0000] {standard_task_runner.py:105} INFO - Job 133: Subtask task_train_model
[2025-02-06T15:17:36.646+0000] {logging_mixin.py:190} WARNING - /opt/conda/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=884) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-06T15:17:36.647+0000] {standard_task_runner.py:72} INFO - Started process 917 to run task
[2025-02-06T15:17:36.724+0000] {task_command.py:467} INFO - Running <TaskInstance: my_training_dag.task_train_model scheduled__2025-01-01T00:21:00+00:00 [running]> on host b98e1e481464
[2025-02-06T15:17:36.829+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_training_dag' AIRFLOW_CTX_TASK_ID='task_train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:21:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:21:00+00:00'
[2025-02-06T15:17:36.830+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-06T15:17:36.831+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-06T15:17:36.831+0000] {logging_mixin.py:190} INFO - Current task name:task_train_model state:running start_date:2025-02-06 15:17:36.578421+00:00
[2025-02-06T15:17:36.832+0000] {logging_mixin.py:190} INFO - Dag name:my_training_dag and current dag run status:running
[2025-02-06T15:17:36.832+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T15:17:36.833+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-06T15:17:36.834+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /root/airflow/train.py']
[2025-02-06T15:17:36.843+0000] {subprocess.py:99} INFO - Output:
[2025-02-06T15:17:42.951+0000] {subprocess.py:106} INFO - [31m2025/02/06 15:17:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.[0m
[2025-02-06T15:17:43.278+0000] {subprocess.py:106} INFO - Index(['id_columns', 'sepal_length', 'sepal_width', 'petal_length',
[2025-02-06T15:17:43.279+0000] {subprocess.py:106} INFO -        'petal_width', 'y'],
[2025-02-06T15:17:43.280+0000] {subprocess.py:106} INFO -       dtype='object')
[2025-02-06T15:17:43.281+0000] {subprocess.py:106} INFO - üèÉ View run classy-foal-955 at: https://quera-server-mlflow-cda209265623.herokuapp.com/#/experiments/265/runs/7275e272f422410aaf6d57bd9dc25cbe
[2025-02-06T15:17:43.281+0000] {subprocess.py:106} INFO - üß™ View experiment at: https://quera-server-mlflow-cda209265623.herokuapp.com/#/experiments/265
[2025-02-06T15:17:43.282+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-02-06T15:17:43.282+0000] {subprocess.py:106} INFO -   File "/root/airflow/train.py", line 24, in <module>
[2025-02-06T15:17:43.283+0000] {subprocess.py:106} INFO -     mlflow.sklearn.log_model(model, "model")
[2025-02-06T15:17:43.284+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/mlflow/sklearn/__init__.py", line 413, in log_model
[2025-02-06T15:17:43.285+0000] {subprocess.py:106} INFO -     return Model.log(
[2025-02-06T15:17:43.285+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^
[2025-02-06T15:17:43.286+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/mlflow/models/model.py", line 866, in log
[2025-02-06T15:17:43.286+0000] {subprocess.py:106} INFO -     mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path, run_id)
[2025-02-06T15:17:43.286+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 1219, in log_artifacts
[2025-02-06T15:17:43.287+0000] {subprocess.py:106} INFO -     MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
[2025-02-06T15:17:43.287+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/mlflow/tracking/client.py", line 2018, in log_artifacts
[2025-02-06T15:17:43.287+0000] {subprocess.py:106} INFO -     self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
[2025-02-06T15:17:43.288+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 875, in log_artifacts
[2025-02-06T15:17:43.288+0000] {subprocess.py:106} INFO -     self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
[2025-02-06T15:17:43.289+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 194, in log_artifacts
[2025-02-06T15:17:43.289+0000] {subprocess.py:106} INFO -     self._upload_file(
[2025-02-06T15:17:43.290+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 169, in _upload_file
[2025-02-06T15:17:43.290+0000] {subprocess.py:106} INFO -     s3_client.upload_file(Filename=local_file, Bucket=bucket, Key=key, ExtraArgs=extra_args)
[2025-02-06T15:17:43.290+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/boto3/s3/inject.py", line 145, in upload_file
[2025-02-06T15:17:43.291+0000] {subprocess.py:106} INFO -     return transfer.upload_file(
[2025-02-06T15:17:43.291+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-02-06T15:17:43.291+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/boto3/s3/transfer.py", line 372, in upload_file
[2025-02-06T15:17:43.291+0000] {subprocess.py:106} INFO -     future.result()
[2025-02-06T15:17:43.292+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/s3transfer/futures.py", line 103, in result
[2025-02-06T15:17:43.292+0000] {subprocess.py:106} INFO -     return self._coordinator.result()
[2025-02-06T15:17:43.292+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-06T15:17:43.293+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/s3transfer/futures.py", line 264, in result
[2025-02-06T15:17:43.293+0000] {subprocess.py:106} INFO -     raise self._exception
[2025-02-06T15:17:43.294+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/s3transfer/tasks.py", line 135, in __call__
[2025-02-06T15:17:43.294+0000] {subprocess.py:106} INFO -     return self._execute_main(kwargs)
[2025-02-06T15:17:43.295+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-06T15:17:43.295+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/s3transfer/tasks.py", line 158, in _execute_main
[2025-02-06T15:17:43.296+0000] {subprocess.py:106} INFO -     return_value = self._main(**kwargs)
[2025-02-06T15:17:43.296+0000] {subprocess.py:106} INFO -                    ^^^^^^^^^^^^^^^^^^^^
[2025-02-06T15:17:43.297+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/s3transfer/upload.py", line 796, in _main
[2025-02-06T15:17:43.297+0000] {subprocess.py:106} INFO -     client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
[2025-02-06T15:17:43.298+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
[2025-02-06T15:17:43.299+0000] {subprocess.py:106} INFO -     return self._make_api_call(operation_name, kwargs)
[2025-02-06T15:17:43.299+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-06T15:17:43.299+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/botocore/client.py", line 1005, in _make_api_call
[2025-02-06T15:17:43.300+0000] {subprocess.py:106} INFO -     http, parsed_response = self._make_request(
[2025-02-06T15:17:43.301+0000] {subprocess.py:106} INFO -                             ^^^^^^^^^^^^^^^^^^^
[2025-02-06T15:17:43.301+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/botocore/client.py", line 1029, in _make_request
[2025-02-06T15:17:43.302+0000] {subprocess.py:106} INFO -     return self._endpoint.make_request(operation_model, request_dict)
[2025-02-06T15:17:43.302+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-06T15:17:43.302+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/botocore/endpoint.py", line 119, in make_request
[2025-02-06T15:17:43.303+0000] {subprocess.py:106} INFO -     return self._send_request(request_dict, operation_model)
[2025-02-06T15:17:43.303+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-06T15:17:43.304+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/botocore/endpoint.py", line 196, in _send_request
[2025-02-06T15:17:43.304+0000] {subprocess.py:106} INFO -     request = self.create_request(request_dict, operation_model)
[2025-02-06T15:17:43.305+0000] {subprocess.py:106} INFO -               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-06T15:17:43.305+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/botocore/endpoint.py", line 132, in create_request
[2025-02-06T15:17:43.306+0000] {subprocess.py:106} INFO -     self._event_emitter.emit(
[2025-02-06T15:17:43.306+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/botocore/hooks.py", line 412, in emit
[2025-02-06T15:17:43.307+0000] {subprocess.py:106} INFO -     return self._emitter.emit(aliased_event_name, **kwargs)
[2025-02-06T15:17:43.307+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-06T15:17:43.307+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/botocore/hooks.py", line 256, in emit
[2025-02-06T15:17:43.308+0000] {subprocess.py:106} INFO -     return self._emit(event_name, kwargs)
[2025-02-06T15:17:43.308+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-06T15:17:43.308+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
[2025-02-06T15:17:43.309+0000] {subprocess.py:106} INFO -     response = handler(**kwargs)
[2025-02-06T15:17:43.309+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^
[2025-02-06T15:17:43.310+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/botocore/signers.py", line 106, in handler
[2025-02-06T15:17:43.310+0000] {subprocess.py:106} INFO -     return self.sign(operation_name, request)
[2025-02-06T15:17:43.311+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-06T15:17:43.311+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/botocore/signers.py", line 198, in sign
[2025-02-06T15:17:43.312+0000] {subprocess.py:106} INFO -     auth.add_auth(request)
[2025-02-06T15:17:43.312+0000] {subprocess.py:106} INFO -   File "/opt/conda/lib/python3.12/site-packages/botocore/auth.py", line 424, in add_auth
[2025-02-06T15:17:43.312+0000] {subprocess.py:106} INFO -     raise NoCredentialsError()
[2025-02-06T15:17:43.313+0000] {subprocess.py:106} INFO - botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2025-02-06T15:17:43.851+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-06T15:17:43.868+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-06T15:17:43.873+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-06T15:17:43.874+0000] {logging_mixin.py:190} INFO - Task start:2025-02-06 15:17:36.578421+00:00 end:2025-02-06 15:17:43.872829+00:00 duration:7.294408
[2025-02-06T15:17:43.874+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): task_train_model> dag:<DAG: my_training_dag> dagrun:<DagRun my_training_dag @ 2025-01-01 00:21:00+00:00: scheduled__2025-01-01T00:21:00+00:00, state:running, queued_at: 2025-02-06 15:17:11.144834+00:00. externally triggered: False>
[2025-02-06T15:17:43.875+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-02-06T15:17:43.875+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=my_training_dag, task_id=task_train_model, run_id=scheduled__2025-01-01T00:21:00+00:00, execution_date=20250101T002100, start_date=20250206T151736, end_date=20250206T151743
[2025-02-06T15:17:43.925+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T15:17:43.926+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 133 for task task_train_model (Bash command failed. The command returned a non-zero exit code 1.; 917)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-06T15:17:43.963+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-06T15:17:43.986+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-06T15:17:43.987+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
